name: Clang Windows Release Mode Unit Test
on: [push, pull_request]

jobs:
  clang-win-release-test:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-clang
      - name: Build environment setup
        run: |
          git clone https://github.com/ravi688/BuildMaster.git
          (cd BuildMaster && ./install_build_master.sh)

      - name: Build
        run: |
          CC=clang CXX=clang++ build_master meson setup release_build --buildtype=release
          CC=clang CXX=clang++ build_master meson compile -C release_build

      - name: Run unit tests
        run: |
          ./unit-test.sh release_build
